package shared

const (
	PROVIDER_OPENAI      = "openai"
	PROVIDER_ANTHROPIC   = "anthropic"
	PROVIDER_GOOGLEAI    = "googleai"
	PROVIDER_COHERE      = "cohere"
	PROVIDER_HUGGINGFACE = "huggingface"
)

var ProviderEnvVars = map[string]string{
	PROVIDER_OPENAI:      "OPENAI_API_KEY",
	PROVIDER_ANTHROPIC:   "ANTHROPIC_API_KEY",
	PROVIDER_GOOGLEAI:    "GOOGLE_API_KEY",
	PROVIDER_COHERE:      "COHERE_API_KEY",
	PROVIDER_HUGGINGFACE: "HUGGINGFACEHUB_API_TOKEN",
}

const (
	DEFAULT_MODEL_OPENAI      = "gpt-4"
	DEFAULT_MODEL_ANTHROPIC   = "claude-3-sonnet-20240229"
	DEFAULT_MODEL_GOOGLEAI    = "gemini-pro"
	DEFAULT_MODEL_COHERE      = "command"
	DEFAULT_MODEL_HUGGINGFACE = "microsoft/DialoGPT-medium"
)

var DefaultModels = map[string]string{
	PROVIDER_OPENAI:      DEFAULT_MODEL_OPENAI,
	PROVIDER_ANTHROPIC:   DEFAULT_MODEL_ANTHROPIC,
	PROVIDER_GOOGLEAI:    DEFAULT_MODEL_GOOGLEAI,
	PROVIDER_COHERE:      DEFAULT_MODEL_COHERE,
	PROVIDER_HUGGINGFACE: DEFAULT_MODEL_HUGGINGFACE,
}
